project_id = "acxhhfwvxtkvxkvmfiep"

[functions.yoco-webhook]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = true

[functions.send-invoice]
verify_jwt = true

[functions.send-payment-link]
verify_jwt = true

[functions.invoices]
verify_jwt = true
